# Generated by Django 5.2.3 on 2025-06-21 18:25

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', django_enum.fields.EnumCharField(choices=[('GENIUS', 'Genius'), ('MUSIXMATCH', 'Musixmatch')], max_length=10)),
                ('external_id', models.IntegerField(null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Source',
                'verbose_name_plural': 'External Sources',
                'constraints': [models.CheckConstraint(condition=models.Q(('source__in', ['GENIUS', 'MUSIXMATCH'])), name='bnt_parser_ExternalSource_source_SourceEnum')],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=127)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('label', models.CharField(max_length=63, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bnt_parser.externalsource')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
            },
        ),
    ]
