# Generated by Django 5.2.3 on 2025-06-21 18:44

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnt_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bnt_parser.externalsource')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='bnt_parser.release')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('type', django_enum.fields.EnumCharField(choices=[('INTRO', 'Intro'), ('VERSE', 'Verse'), ('PRECHORUS', 'Pre-Chorus'), ('CHORUS', 'Chorus'), ('BRIDGE', 'Bridge'), ('CODA', 'Coda'), ('OUTRO', 'Outro')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bnt_parser.song')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['INTRO', 'VERSE', 'PRECHORUS', 'CHORUS', 'BRIDGE', 'CODA', 'OUTRO'])), name='bnt_parser_Section_type_SectionTypeEnum')],
            },
        ),
    ]
