# Generated by Django 5.2.3 on 2025-11-05 22:52

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnt_parser', '0004_line_word'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='bnt_parser_Section_type_SectionTypeEnum',
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('INTRO', 'Intro'), ('VERSE', 'Verse'), ('PRECHORUS', 'Pre-Chorus'), ('CHORUS', 'Chorus'), ('POSTCHORUS', 'Post-Chorus'), ('BRIDGE', 'Bridge'), ('CODA', 'Coda'), ('OUTRO', 'Outro'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='bnt_parser.release'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['INTRO', 'VERSE', 'PRECHORUS', 'CHORUS', 'POSTCHORUS', 'BRIDGE', 'CODA', 'OUTRO', 'OTHER'])), name='bnt_parser_Section_type_SectionTypeEnum'),
        ),
    ]
