# Generated by Django 5.2.3 on 2025-11-06 22:55

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnt_parser', '0005_remove_section_bnt_parser_section_type_sectiontypeenum_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='bnt_parser_Section_type_SectionTypeEnum',
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('INTRO', 'Intro'), ('VERSE', 'Verse'), ('PRECHORUS', 'Pre-Chorus'), ('CHORUS', 'Chorus'), ('POSTCHORUS', 'Post-Chorus'), ('BRIDGE', 'Bridge'), ('BREAKDOWN', 'Breakdown'), ('SPOKEN', 'Spoken'), ('CODA', 'Coda'), ('OUTRO', 'Outro'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['INTRO', 'VERSE', 'PRECHORUS', 'CHORUS', 'POSTCHORUS', 'BRIDGE', 'BREAKDOWN', 'SPOKEN', 'CODA', 'OUTRO', 'OTHER'])), name='bnt_parser_Section_type_SectionTypeEnum'),
        ),
    ]
