# Generated by Django 5.2.3 on 2026-08-02 15:44

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnt_parser', '0006_remove_section_bnt_parser_section_type_sectiontypeenum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', django_enum.fields.EnumCharField(choices=[('GENIUS', 'Genius'), ('MUSIXMATCH', 'Musixmatch')], max_length=10)),
                ('external_id', models.IntegerField(null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('reason', django_enum.fields.EnumCharField(choices=[('TRANSLATION', 'Translation of another song'), ('NON_MUSIC', 'Tagged Non-Music'), ('NO_LYRICS', 'No lyrics found on page')], max_length=11)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rejected Track',
                'verbose_name_plural': 'Rejected Tracks',
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_rejected_track'), models.CheckConstraint(condition=models.Q(('source__in', ['GENIUS', 'MUSIXMATCH'])), name='bnt_parser_RejectedTrack_source_SourceEnum'), models.CheckConstraint(condition=models.Q(('reason__in', ['TRANSLATION', 'NON_MUSIC', 'NO_LYRICS'])), name='bnt_parser_RejectedTrack_reason_ReasonEnum')],
            },
        ),
    ]
