# Generated by Django 5.2.3 on 2026-08-04 21:02

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnt_parser', '0007_rejectedtrack'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rejectedtrack',
            name='bnt_parser_RejectedTrack_reason_ReasonEnum',
        ),
        migrations.AlterField(
            model_name='rejectedtrack',
            name='reason',
            field=django_enum.fields.EnumCharField(choices=[('TRANSLATION', 'Translation of another song'), ('NON_MUSIC', 'Tagged Non-Music'), ('NO_LYRICS', 'No lyrics found on page'), ('PAGE_GONE', 'Genius page no longer exists')], max_length=11),
        ),
        migrations.AddConstraint(
            model_name='rejectedtrack',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['TRANSLATION', 'NON_MUSIC', 'NO_LYRICS', 'PAGE_GONE'])), name='bnt_parser_RejectedTrack_reason_ReasonEnum'),
        ),
    ]
