# Generated by Django 5.2.3 on 2026-05-17 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordVariantLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=63, unique=True)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Word Variant Lookup',
                'verbose_name_plural': 'Word Variant Lookups',
            },
        ),
        migrations.CreateModel(
            name='WordVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='bnt_searcher.wordvariantlookup')),
            ],
            options={
                'verbose_name': 'Word Variant',
                'verbose_name_plural': 'Word Variants',
                'constraints': [models.UniqueConstraint(fields=('lookup', 'text'), name='unique_variant_per_lookup')],
            },
        ),
    ]
